[package]

name = "rust-ascii-march"
version = "0.0.1"
authors = ["Peter Jacobs <peter@crespyl.net>"]

[dependencies]
rand = "*"
noise = "*"
rustbox = "*"
hlua = "*"
notify = "4.0.0"

[[bin]]
name = "ascii-march"
path = "src/main.rs"
